const jobsList = [
    {"jobDescription": "Brakes, All", "plannedTime": 3.0, "partsCost": 300},
    {"jobDescription": 'Brakes, Front(Both)', "plannedTime": 1.5, "partsCost": 150},
    {"jobDescription": 'Brakes, Back(Both)', "plannedTime": 1.5 , "partsCost": 150},
    {"jobDescription": 'Lights, Headlight', "plannedTime": 0.5 , "partsCost": 50},
    {"jobDescription": 'Hoses, Cooling', "plannedTime": 2.0 , "partsCost": 48},
    {"jobDescription": 'Belts, All', "plannedTime": 1 , "partsCost": 32},
    {"jobDescription": 'Belts, One', "plannedTime": 0.5 , "partsCost": 50},
    {"jobDescription": 'Exhaust, Muffler', "plannedTime": 2.0 , "partsCost": 200},
    {"jobDescription": 'Suspension, Shocks(All)', "plannedTime": 1.5 , "partsCost": 244},
    {"jobDescription": 'Cooling System, Radiator', "plannedTime": 3.8 , "partsCost": 485},
    {"jobDescription": 'Tires, All', "plannedTime": 1 , "partsCost": 200},
    {"jobDescription": 'Tires, Front(Both)', "plannedTime": 0.5 , "partsCost": 100},
    {"jobDescription": 'Tires, Back(Both)', "plannedTime": 0.5 , "partsCost": 100},
    {"jobDescription": 'Oil Change', "plannedTime": 0.5 , "partsCost": 20},
    {"jobDescription": 'Engine, Engine Assembly', "plannedTime": 10.0 , "partsCost": 5020},
    {"jobDescription": 'Engine, Engine Block', "plannedTime": 6.0 , "partsCost": 3000},
    {"jobDescription": 'Electrical, Wiring Harness', "plannedTime": 4.0 , "partsCost": 415},
    {"jobDescription": 'Electrical, Alternator', "plannedTime": 1.0 , "partsCost": 158},
    {"jobDescription": 'Electrical, Starter', "plannedTime": 2.0 , "partsCost": 110},
    {"jobDescription": 'Electrical, Battery', "plannedTime": 0.5 , "partsCost": 88},
    {"jobDescription": 'Transmission, Transmission Assembly', "plannedTime": 4.5 , "partsCost": 2587},
    {"jobDescription": 'Transmission, Clutch', "plannedTime": 2.5 , "partsCost": 1849},

]
